Repository wecode-bootcamp-korea/22-1st-mangoPeace-frontend, pull requests merged in 2021-07, with the labels that each got.

#6 [22기 정빛열음] Add: Footer 레이아웃 완료
  src/Routes.js
  src/components/Footer.js
  src/components/Footer.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#3 [22기 이의연] MOD: Nav 생성 및 레이아웃 구현 & 리뷰 수정
  public/images/profile_img.png
  src/components/Nav.js
  src/components/Nav.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#10 [22기 이의연] MOD: bestlist 페이지 display 속성 변경
  src/pages/BestList/BestList.js
  src/pages/BestList/BestList.scss
Labels: Status: 리뷰 요청

#11 [22기 이경민] 로그인 css 수정
  src/pages/Login/Login.scss
Labels: Status: Accepted

#8 [22기 이의연] MOD: 메인 페이지 기능구현완료 & 1차 리뷰 수정
  src/pages/Main/FoodThemeListSection/BestListImg/BestListImg.js
  src/pages/Main/FoodThemeListSection/BestListImg/BestListImg.scss
  src/pages/Main/FoodThemeListSection/FoodThemeListSection.js
  src/pages/Main/FoodThemeListSection/FoodThemeListSection.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainImgBar/MainImgBar.js
  src/pages/Main/MainImgBar/MainImgBar.scss
  src/pages/Main/PopStoreSection/PopStore/PopStore.js
  src/pages/Main/PopStoreSection/PopStore/PopStore.scss
  src/pages/Main/PopStoreSection/PopStoreSection.js
  src/pages/Main/PopStoreSection/PopStoreSection.scss
Labels: Status: 리뷰 요청

#7 [22기 정빛열음] Add: Detail 레이아웃 완료, 기능 구현 진행 중
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/StoreImgBox/StoreImgBox.js
  src/pages/Detail/StoreImgBox/StoreImgBox.scss
  src/pages/Detail/StoreInfo/StoreHeader/StoreHeader.js
  src/pages/Detail/StoreInfo/StoreHeader/StoreHeader.scss
  src/pages/Detail/StoreInfo/StoreInfo.js
  src/pages/Detail/StoreInfo/StoreInfo.scss
  src/pages/Detail/StoreInfo/StoreInfoTable/StoreInfoTable.js
  src/pages/Detail/StoreInfo/StoreInfoTable/StoreInfoTable.scss
  src/pages/Detail/StoreInfo/StoreLocation/StoreLocation.js
  src/pages/Detail/StoreInfo/StoreLocation/StoreLocation.scss
  src/pages/Detail/StoreReviewBox/ReviewInput/ReviewInput.js
  src/pages/Detail/StoreReviewBox/ReviewInput/ReviewInput.scss
  src/pages/Detail/StoreReviewBox/ReviewLi/ReviewLi.js
  src/pages/Detail/StoreReviewBox/ReviewLi/ReviewLi.scss
  src/pages/Detail/StoreReviewBox/StoreReviewBox.js
  src/pages/Detail/StoreReviewBox/StoreReviewBox.scss
Labels: Status: Accepted

#12 [22기 정빛열음] Add: wishList 레이아웃
  src/components/WishLisit/WishList.js
  src/components/WishLisit/WishList.scss
  src/components/WishLisit/WishListEmpty/WishListEmpty.js
  src/components/WishLisit/WishListEmpty/WishListEmpty.scss
  src/components/WishLisit/WishListLi/WishListLi.js
  src/components/WishLisit/WishListLi/WishListLi.scss
Labels: Status: 리뷰 요청

#14 [22기 이의연] Nav 리뷰 수정 & 로그인/회원가입 라우팅
  src/components/Nav.js
  src/components/Nav.scss
  src/pages/BestList/BannerList/StoreCard/StoreCard.js
Labels: Status: 리뷰 요청

#15 [22기 정빛열음] Modify: 리팩토링 진행 중
  .env
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/StoreImgBox/StoreImgBox.js
  src/pages/Detail/StoreInfo/StoreHeader/StoreHeader.js
  src/pages/Detail/StoreInfo/StoreInfo.js
  src/pages/Detail/StoreInfo/StoreInfoTable/StoreInfoTable.js
  src/pages/Detail/StoreInfo/StoreLocation/StoreLocation.js
  src/pages/Detail/StoreReviewBox/ReviewEmpty/ReviewEmpty.js
  src/pages/Detail/StoreReviewBox/ReviewEmpty/ReviewEmpty.scss
  src/pages/Detail/StoreReviewBox/ReviewInput/RatingStar/RatingStar.js
  src/pages/Detail/StoreReviewBox/ReviewInput/RatingStar/RatingStar.scss
  src/pages/Detail/StoreReviewBox/ReviewInput/ReviewInput.js
  src/pages/Detail/StoreReviewBox/ReviewInput/ReviewInput.scss
  src/pages/Detail/StoreReviewBox/ReviewLi/ReviewLi.js
  src/pages/Detail/StoreReviewBox/StoreReviewBox.js
  src/pages/Detail/StoreReviewBox/StoreReviewBox.scss
  src/utilities/query.js
Labels: Status: 리뷰 요청

#16 [22기 정빛열음] Add: config 추가
  src/config.js
Labels: Status: 리뷰 요청

#13 [22기 이의연] bestlist style 변경 및 fetch함수 적용 후 통신 완료
  public/images/muyaho.jpeg
  src/pages/BestList/BannerList/BannerList.js
  src/pages/BestList/BannerList/BannerList.scss
  src/pages/BestList/BannerList/StoreCard/StoreCard.js
  src/pages/BestList/BannerList/StoreCard/StoreCard.scss
  src/pages/BestList/BannerTitle/BannerTitle.js
  src/pages/BestList/BannerTitle/BannerTitle.scss
  src/pages/BestList/BestList.js
  src/pages/BestList/BestList.scss
Labels: Status: Accepted

#18 [22기 정빛열음] Modify: Nav 수정
  public/images/logo.png
  src/Routes.js
  src/components/Nav.js
  src/components/Nav/MyProfile/MyProfile.js
  src/components/Nav/MyProfile/MyProfile.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/SignBox/SignBox.js
  src/components/Nav/SignBox/SignBox.scss
  src/components/WishList/WishList.js
  src/components/WishList/WishList.scss
  src/components/WishList/WishListEmpty/WishListEmpty.js
  src/components/WishList/WishListEmpty/WishListEmpty.scss
  src/components/WishList/WishListLi/WishListLi.js
  src/components/WishList/WishListLi/WishListLi.scss
Labels: Status: 리뷰 요청

#19 [22기 정빛열음] Modify: config 내 BASE_URL 적용
  src/pages/Detail/Detail.js
  src/pages/Detail/StoreInfo/StoreHeader/StoreHeader.js
  src/pages/Detail/StoreReviewBox/ReviewInput/ReviewInput.js
Labels: Status: 리뷰 요청

#20 [22기 이의연] Feature/best list 라우팅 경로 설정
  src/config.js
  src/pages/BestList/BannerList/StoreCard/StoreCard.js
  src/pages/BestList/BannerTitle/BannerTitle.js
  src/pages/BestList/BestList.js
  src/pages/Main/bannerText.js
Labels: Status: 리뷰 요청

#22 [22기 이의연] Feature/main 메인페이지 라우팅 및 구현 완료
  src/pages/BestList/BannerList/StoreCard/StoreCard.js
  src/pages/Detail/StoreReviewBox/ReviewEmpty/ReviewEmpty.js
  src/pages/Main/FoodThemeListSection/BestListImg/BestListImg.js
  src/pages/Main/FoodThemeListSection/FoodThemeListSection.js
  src/pages/Main/Main.js
  src/pages/Main/MainImgBar/MainImgBar.js
  src/pages/Main/PopStoreSection/PopStore/PopStore.js
  src/pages/Main/PopStoreSection/PopStoreSection.scss
Labels: Status: 리뷰 요청

#21 [22기 정빛열음] Modify: nav 스타일 변경 로직 수정
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#23 [22기 이의연] bestlist 라우팅 경로 설정 test 중 (merge 후 테스트 가능!)
  src/config.js
  src/pages/BestList/BannerList/StoreCard/StoreCard.js
  src/pages/BestList/BannerTitle/BannerTitle.js
  src/pages/Main/bannerText 2.js
Labels: Status: 리뷰 요청

#25 [22기 이의연] 라우팅 해결완료 & style 수정
  src/pages/BestList/BannerList/StoreCard/StoreCard.js
  src/pages/BestList/BannerList/StoreCard/StoreCard.scss
  src/pages/BestList/BannerTitle/BannerTitle.js
  src/pages/BestList/BestList.js
  src/pages/Main/FoodThemeListSection/BestListImg/BestListImg.js
  src/pages/Main/MainImgBar/MainImgBar.js
  src/pages/Main/bannerText 2.js
  src/pages/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#1 [22기 이경민] 필터 기능 구현중
  src/Routes.js
  src/pages/Filter/Filter.js
  src/pages/Filter/Filter.scss
  src/pages/FilterComponent/MenuCategorySelectSection.js
  src/pages/FilterComponent/PriceSelectSection.js
  src/pages/FilterComponent/SelectRatingSection.js
  src/pages/Login/Login.scss
  src/pages/SearchResult/PagingButtonComponent.js
  src/pages/SearchResult/SearchResult.js
  src/pages/SearchResult/SearchResult.scss
  src/pages/SearchResultComponent/SearchResultListComponent.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#26 [22기 정빛열음] Hotfix: 로그인, 회원가입 수정 및 모달화
  src/Routes.js
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#29 [Feature/search result] SearchResult 머지 요청
  src/pages/Filter/Filter.js
  src/pages/SearchResult/SearchResult.js
  src/pages/SearchResult/SearchResult.scss
Labels: Status: 도움 요청, Status: 리뷰 요청
